apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: microservices
  labels:
    app: notification-service
spec:
  type: NodePort
  ports:
    - port: 8003
      targetPort: 8003
      nodePort: 30003
  selector:
    app: notification-service
